### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by steveoh** [utahdts/utah-design-system#144]
This is visible in npm as well as the github rendered readme

https://github.com/utahdts/utah-design-system/blob/409479d0ad2c8d6cbf8aa6cfbbcc3f046c78c886/%40utahdts/utah-design-system-header/README.md?plain=1#L73

**Comment by AustinHaws-Utah** [comment]
Those links are definitely bad. We are going to update the readMes to be useful.

UDS-1018

**Comment by AustinHaws-Utah** [comment]
Fixed in release 1.1.0
