### ISSUE TITLE
Props for Table React components are unclear in documentation

### ISSUE THREAD

**Issue by agilvarry** [utahdts/utah-design-system#186]
On the page for the [Table component](https://designsystem.utah.gov/library/components/table) the example React code includes props but doesn't give any example or type.

example: stateSymbols in the example below isn't described at all.
``` JavaScript
<TableBodyData records={stateSymbols} recordIdField="category">
        <TableBodyDataRowTemplate>
          <TableBodyDataCellTemplate recordFieldPath="category" />
          <TableBodyDataCellTemplate recordFieldPath="symbol" />
          <TableBodyDataCellTemplate recordFieldPath="year" />
        </TableBodyDataRowTemplate>
      </TableBodyData>
```

**Comment by AustinHaws-Utah** [comment]
Here's the code for the full example:
https://github.com/utahdts/utah-design-system/blob/dev/utah-design-system-website/src/react/components/websiteContent/library/components/table/TableExampleRender.jsx

`stateSymbols` is an object of state symbol information:
```
const stateSymbols = [
  { category: 'Bird', symbol: 'California Seagull', year: 1955 },
  { category: 'Emblem', symbol: 'Beehive', year: 1959 },
  { category: 'Folk Dance', symbol: 'Square Dance', year: 1994 },
  { category: 'Fruit', symbol: 'Cherry', year: 1997 },
  ...
```

**Comment by AustinHaws-Utah** [comment]
New Jira Issue: UDS-1122
