### ISSUE TITLE
Header mobile menu width is greater than the page width. 

### ISSUE THREAD

**Issue by jbehling-dts** [utahdts/utah-design-system#247]
When the browser window is resized to a small enough width to activate the hamburger menu, the div with this class "utds-header-mobile-menu" gets a width larger than the page causing a horizontal scroll bar to appear. This only happens on the normal browser; it doesn't happen when I emulate a mobile device using DevTools. I found that if I change the css for "utds-header-mobile-menu" from "width: 100vw;" to "width: 100%;", it fixes the issue.
![mobile-menu-extended-width](https://github.com/utahdts/utah-design-system/assets/137916312/3ee75d98-5786-4e42-b8f1-aa1b52d8c0c0)
![mobile-menu-css](https://github.com/utahdts/utah-design-system/assets/137916312/f2031edd-38a8-43e0-905b-e8af209efbe6)

**Comment by jmsharp-utah** [comment]
Verified this will fix it. The reason we didn't see it is because I never have scrollbars turned on. That is the difference between `100vw` and `100%`. Dumb browsers.

**Comment by AustinHaws-Utah** [comment]
This work has been completed and released.
