### ISSUE TITLE
Offical Website utah.gov image options

### ISSUE THREAD

**Issue by AustinHaws-Utah** [utahdts/utah-design-system#300]
Steve Gourley:
The Offical Website popup in shows an image of a utah.gov url. The blurred first part of the url is 'designsystem' (with '.utah.gov' after it). Maybe it'd be worthwhile to make that url less specific and more generic. `id.utah.gov`? Or maybe could blur out the first part of the url to make illegible.

Joseph Sharp: Also, Google has updated their lock icon so a new image is needed anyway.

UDS-1435

**Comment by steveoh** [comment]
There are more browsers than chrome :)

Here are two of many just for fun.

- <img width="120" alt="image" src="https://github.com/utahdts/utah-design-system/assets/325813/0af9331a-66b1-41ba-9886-9486588ba901">
- ![image](https://github.com/utahdts/utah-design-system/assets/325813/446d9009-16ad-4ff2-8911-881bd7a4866c)

**Comment by AustinHaws-Utah** [comment]
Currently slated for sprint 4, finishing Feb 27

**Comment by AustinHaws-Utah** [comment]
Now slated for the next spring 2024Q4S3

**Comment by AustinHaws-Utah** [comment]
This is now planned work in our current 2024Q4S4 sprint.

**Comment by AustinHaws-Utah** [comment]
Slipped to the new current sprint: 2024Q4S5

**Comment by AustinHaws-Utah** [comment]
Work is done. waiting on release

**Comment by AustinHaws-Utah** [comment]
this has (finally) been released in 2.0.0

**Comment by steveoh** [comment]
What is the solution? And 2.0! WHAAAAAAAAAAT

**Comment by AustinHaws-Utah** [comment]
you can see it on the site, but here's a screen shot:
![Screenshot 2024-08-01 at 17 05 33](https://github.com/user-attachments/assets/eec81b2f-3923-4532-a6c1-4a33e8c93bbc)

and yes. 2.0 is official! we made it! now we can start doing "real" semantic version changes. 😌

**Comment by steveoh** [comment]
It looks the same? What changed

**Comment by AustinHaws-Utah** [comment]
The icon, the url, and the blurriness factor have changed.
