### ISSUE TITLE
Should this be `flex-start`?

### ISSUE THREAD

**Issue by stdavis** [utahdts/utah-design-system#309]
https://github.com/utahdts/utah-design-system/blob/b1262b7d08a69652ff61e963ed0147a4d1f83d23/%40utahdts/utah-design-system/css/6-components/base-components/forms/_multi-select-input.scss#L16

I'm getting the following warning in my Vite console:
![image](https://github.com/utahdts/utah-design-system/assets/1326248/a01a119a-74a7-4ac9-b255-43da13149731)

I searched the code base for this project and found the line above. I wonder if it would be better/more explicit to change the value from `start` to `flex-start`?

[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#flex-start) (may or may not be helpful)

**Comment by jmsharp-utah** [comment]
Yes. 👍 
Will fix.

**Comment by AustinHaws-Utah** [comment]
Now released in v1.13.3!
