### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by steveoh** [utahdts/utah-design-system#310]
View on the [footer page](https://designsystem.utah.gov/library/utahFooter)

<img width="512" alt="image" src="https://github.com/utahdts/utah-design-system/assets/325813/aed74e19-5bfe-4748-ba0d-4693cc9388b7">

**Comment by AustinHaws-Utah** [comment]
this one?
![Screenshot 2024-01-10 at 16 38 41](https://github.com/utahdts/utah-design-system/assets/77676718/b7f76573-7119-4c82-a1ab-700e756d6d39)

**Comment by steveoh** [comment]
silly ad blocker
