### ISSUE TITLE
Certain header icons create horizontal scroll buffer on right side of screen (desktop)

### ISSUE THREAD

**Issue by sherzog-tyler** [utahdts/utah-design-system#397]
Recreate issue:

- Go to Utah Header configuration.
- Select "**Help**" icon under _Action Items_
- Space now appears outside of window allowing for horizontal scroll

This happens when any header is configured to use a "Help" action.  I'm not sure if the issue persists for other actions.

Screenshot (firefox)

![Screenshot 2024-08-05 at 2 06 33 PM](https://github.com/user-attachments/assets/8e97ed92-c1c8-4e89-a742-ec5cc3fecb4c)

**Comment by AustinHaws-Utah** [comment]
reproduced! looking at options...

**Comment by jmsharp-utah** [comment]
Fixed in 2.0.1
