### ISSUE TITLE
TabGroup onChange function breaks React component

### ISSUE THREAD

**Issue by agilvarry** [utahdts/utah-design-system#408]
I've been working to incorporate more of the Design System components into https://stip.udot.utah.gov/ and I believe I've found a bug where if you attempt to use the "onChange" property of the TabGroup component it ceases to change tabs when you click on a new one.  I attempted to change the "value" property to get around this to no avail.

**Comment by AustinHaws-Utah** [comment]
reproduced! working on a fix.

**Comment by AustinHaws-Utah** [comment]
Fix released in version 2.0.3. Give it a shot and let us know!
