### ISSUE TITLE
Checkboxes get squished when the label is larger than the parent

### ISSUE THREAD

**Issue by stdavis** [utahdts/utah-design-system#90]
![image](https://user-images.githubusercontent.com/1326248/234610254-b4503b55-77e2-45bc-ada3-fea8a3c48312.png)

Here's the markup for the checkbox:
```jsx
<div className="input-wrapper input-wrapper--checkbox">
    <label htmlFor={id}>{config[fieldNames.queryLayers.name]}</label>
    <input type="checkbox" id={id} />
</div>
```

I think that maybe a `flex-shrink: 0` might need to be added to `input[type=checkbox]` to fix this.

**Comment by AustinHaws-Utah** [comment]
Excellent information! We'll take a look at this.

UDS-687

**Comment by AustinHaws-Utah** [comment]
UDS-996
