### ISSUE TITLE
Consider remove console.log of version number

### ISSUE THREAD

**Issue by steveoh** [utahdts/utah-design-system#91]
Would you entertain moving the version into the html markup? e.g. as a hidden element or alt tag.

https://github.com/utahdts/utah-design-system/blob/e5c29ad9c18c575d46b1f086f3fda2e5c703986c/%40utahdts/utah-design-system-header/src/index.js#L6

**Comment by AustinHaws-Utah** [comment]
This has been helpful for us for debugging and troubleshooting purposes. Now that the header is close to emerging to adulthood, it may be better for us to add some sort of "easter egg" version reporter instead of always console logging it. @jmsharp-utah what do you think?

**Comment by AustinHaws-Utah** [comment]
We will remove the console.log... eventually.

UDS-695

**Comment by AustinHaws-Utah** [comment]
It has been removed! You should now be seeing no console logs from the header! Please give it a try and let us know. It appears this was released in version 0.9.5

**Comment by steveoh** [comment]
Gracias amigo. We'll check it out. It's so minor that I'm happy to close this out before looking. You could reference #91 so we can see the changes in the commits that fixed it. Did you move the version somewhere else?

**Comment by AustinHaws-Utah** [comment]
Ya, messed up not putting #91 on the commit 🤦 The version is in the package.json... but it's not displayed in the header. for now. 🙊

**Comment by steveoh** [comment]
We updated and it looks good!
