### ISSUE TITLE
Checkbox wrapping alignment issue?

### ISSUE THREAD

**Issue by steveoh** [utahdts/utah-design-system#92]
https://github.com/utahdts/utah-design-system/blob/e5c29ad9c18c575d46b1f086f3fda2e5c703986c/%40utahdts/utah-design-system/css/6-components/base-components/forms/_checkbox.scss#L60

Setting this to center in my opinion looks silly. Please let me know if this is by design.

Would adding a `margin-top: 2px;` (or some rem value if font size needs to be taken into account) on the checkbox and `align-items: flex-start;` to the `.input-wrapper` container make it read better?

e.g.

![image](https://user-images.githubusercontent.com/325813/234641640-5ceeb9d9-d8d7-463c-b86a-2841ca0e6d55.png) vs ![image](https://user-images.githubusercontent.com/325813/234641674-3dd70be0-e0f4-4614-87ef-e1d618cb98d7.png)

**Comment by AustinHaws-Utah** [comment]
We have not yet got to this component to create its css and guidelines. We bootstrapped some components, but they are not refined nor official. Checkbox is one of them. So, yes this will be changed... when it's number is called by the Sprint gods.

**Comment by steveoh** [comment]
Thanks for the explanation @AustinHaws-Utah.

Since it's not simple to know the components that are refined or official, what do you think about removing all styling for components that haven't been worked on yet? 

Or better yet, since we're only trying to use the header, remove all the styles that don't participate in making the header display properly?

**Comment by AustinHaws-Utah** [comment]
Since this is "alpha", we'll probably wait to pull stuff out until we've got the base structure in place. At that time, we will be in a better place to refactor out unused css. Especially with the header only needing pieces of the design system and not the whole big bundle.

**Comment by jmsharp-utah** [comment]
Was fixed in a previous release. (1.11.0?)
